version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint

  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py
artifacts:
  files:
    - target/messageUtil-1.0.jar
